"""Generate version_info.txt, the Windows version resource for the PyInstaller exe.

Run after bumping __version__ in src/portable_manager/__init__.py:

    python tools/make_version_info.py

The version is parsed with a regex rather than imported, so this works without
the app's dependencies installed. Standard library only.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INIT_FILE = REPO_ROOT / "src" / "portable_manager" / "__init__.py"
OUTPUT_FILE = REPO_ROOT / "version_info.txt"

PRODUCT_NAME = "Portable Program Manager"
COMPANY_NAME = "Alex Stapleton"
FILE_DESCRIPTION = "Portable Program Manager"
INTERNAL_NAME = "PortableProgramManager"
ORIGINAL_FILENAME = "PortableProgramManager.exe"
LEGAL_COPYRIGHT = "GPL-3.0"

_VERSION_LINE_RE = re.compile(r"""^__version__\s*=\s*["']([^"']+)["']""", re.MULTILINE)
# Leading numeric part only: "0.8.0" -> "0.8.0"; "0.8.0-beta.1" -> "0.8.0".
_NUMERIC_VERSION_RE = re.compile(r"\d+(?:\.\d+){0,3}")

TEMPLATE = """# UTF-8
# Generated by tools/make_version_info.py. Do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tuple_str},
    prodvers={tuple_str},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company}'),
        StringStruct('FileDescription', '{description}'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', '{internal}'),
        StringStruct('LegalCopyright', '{copyright}'),
        StringStruct('OriginalFilename', '{original}'),
        StringStruct('ProductName', '{product}'),
        StringStruct('ProductVersion', '{version}')])
      ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def read_version() -> str:
    match = _VERSION_LINE_RE.search(INIT_FILE.read_text(encoding="utf-8"))
    if match is None:
        raise SystemExit(f"__version__ not found in {INIT_FILE}")
    return match.group(1)


def four_part_version(version: str) -> tuple[int, int, int, int]:
    """Convert '0.8.0' to (0, 8, 0, 0), padding with zeros to four parts."""
    match = _NUMERIC_VERSION_RE.match(version)
    if match is None:
        raise SystemExit(f"Cannot parse version {version!r} as numbers")
    parts = [int(part) for part in match.group(0).split(".")]
    parts += [0] * (4 - len(parts))
    return tuple(parts)  # type: ignore[return-value]


def main() -> None:
    version = read_version()
    numbers = four_part_version(version)
    dotted = ".".join(str(n) for n in numbers)

    text = TEMPLATE.format(
        tuple_str=repr(numbers),
        company=COMPANY_NAME,
        description=FILE_DESCRIPTION,
        version=dotted,
        internal=INTERNAL_NAME,
        copyright=LEGAL_COPYRIGHT,
        original=ORIGINAL_FILENAME,
        product=PRODUCT_NAME,
    )
    OUTPUT_FILE.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_FILE} (version {version} -> {dotted})")


if __name__ == "__main__":
    main()
